/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BMICalculator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Koket
 */
public class BMICalculator1 extends javax.swing.JFrame {
  ResultSet rs = null;
   int a=0;
    /**
     * Creates new form BMICalculator1
     */
    public BMICalculator1() {
        initComponents();
    }

    //creating class for database connection
       public class DBConnection{
           //declaring values for database connection
        Connection con = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String url = "jdbc:mysql://localhost:4306/hospital?zeroDateTimeBehavior=CONVERT_TO_NULL";
        String password = "";
        String username = "root";
        
        public ResultSet find(String s){
            
            try{
            con = DriverManager.getConnection(url,username,password);
            pst = con.prepareStatement("select * from patient where Patient_ID = ?");
            pst.setString(1, s);
            rs= pst.executeQuery();
        
        }catch(SQLException ie){
    JOptionPane.showMessageDialog(null,ie.getMessage());
}return rs;
        }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        PatientIDlbl = new javax.swing.JLabel();
        PatientIDtf = new javax.swing.JTextField();
        Namelbl = new javax.swing.JLabel();
        Nametf = new javax.swing.JTextField();
        Genderlbl = new javax.swing.JLabel();
        Gendertf = new javax.swing.JTextField();
        MRadioButton = new javax.swing.JRadioButton();
        FRadioButton = new javax.swing.JRadioButton();
        Weightlbl = new javax.swing.JLabel();
        Weighttf = new javax.swing.JTextField();
        Heightlbl = new javax.swing.JLabel();
        Heighttf = new javax.swing.JTextField();
        Messagelbl = new javax.swing.JLabel();
        Messagetf = new javax.swing.JTextField();
        CalculateBMI = new javax.swing.JButton();
        Displaybutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient BMI Calculator");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setToolTipText("");

        PatientIDlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PatientIDlbl.setText("Patient_ID");

        Namelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Namelbl.setText("Name");

        Nametf.setEditable(false);

        Genderlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Genderlbl.setText("Gender");

        Gendertf.setEditable(false);

        MRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(MRadioButton);
        MRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MRadioButton.setText("Male");

        FRadioButton.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(FRadioButton);
        FRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FRadioButton.setText("Female");

        Weightlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Weightlbl.setText("Weight in Kg");

        Weighttf.setEditable(false);

        Heightlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Heightlbl.setText("Height in metres");

        Heighttf.setEditable(false);

        Messagelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Messagelbl.setText("Message");

        Messagetf.setEditable(false);

        CalculateBMI.setText("Calculate BMI");
        CalculateBMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBMIActionPerformed(evt);
            }
        });

        Displaybutton.setText("Display");
        Displaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Namelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PatientIDlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Genderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Weightlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(MRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(2, 2, 2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Weighttf)
                    .addComponent(Heighttf)
                    .addComponent(Gendertf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nametf)
                    .addComponent(PatientIDtf, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CalculateBMI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(Messagelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Displaybutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Messagetf))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PatientIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientIDtf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nametf, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Genderlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gendertf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(FRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Weightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Weighttf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Heightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Heighttf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Messagetf, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(Messagelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Displaybutton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(CalculateBMI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybuttonActionPerformed
     //calling the Database connection class
        DBConnection  db = new DBConnection();
 //retrieving data from phpmyadmin mySql and setting them to their respective compnents for display
        rs=db.find(PatientIDtf.getText());

        try{
           
            if(rs.next()){
                //displaying message
                JOptionPane.showMessageDialog(null,"The patient's record was successfully displayed!");
                String name = rs.getString("Name");
                Nametf.setText(name);
                String Gtf = rs.getString("Gender");
                Gendertf.setText(Gtf);
                String GRadiobutton = rs.getString("Gender");
                if(GRadiobutton.equals("Female")){
                    MRadioButton.setSelected(false);
                    FRadioButton.setSelected(true);
                }else{
                    FRadioButton.setSelected(false);
                    MRadioButton.setSelected(true);
                }
                String W = rs.getString("Weight");

                Weighttf.setText(W);
                String H = rs.getString("Height");
                Heighttf.setText(H);

            }else{
                JOptionPane.showMessageDialog(null,"No data found for this ID");
            }

        }catch(Exception ie){
            JOptionPane.showMessageDialog(null,ie.getMessage());
        }
    }//GEN-LAST:event_DisplaybuttonActionPerformed
//creating action for when the calulate button is clicked
    private void CalculateBMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBMIActionPerformed
     //fetching values from the display action performed
        String gender = Gendertf.getText();
       String weight = Weighttf.getText();
        String height = Heighttf.getText();
        
         
     if (gender.equals("Female")){
         //Calculating female bmi
         //changing the strings fetched into double to calulate bmi
            double w = Double.parseDouble(weight);
         double h = Double.parseDouble(height);
         //declaring formula for bmi
         double bmi = w/(h*h);
         //diplaying the bmi result
         JOptionPane.showMessageDialog(null,"Your BMI is: "+bmi);
        
                //displayin the category by bmi amount in message textfield 
         if(bmi<18.5){
             Messagetf.setText("You are Underweight");
         }else if(bmi>18.5 && bmi< 24.5){
             Messagetf.setText("You are Ideal Weight");
         }else if (bmi>24.5 && bmi< 39.9){
             Messagetf.setText("You are Over Weight");
         }else{
          Messagetf.setText("You are Obese");
     }
         
     }else{
      //calculating male bmi
      
       //changing the strings fetched into double to calulate bmi
             double w = Double.parseDouble(weight);
         double h = Double.parseDouble(height);
         
         double bmi = w/(h*h);
            //displayin the category by bmi amount in message textfield 
         if(bmi<22.5){
             Messagetf.setText("You are Underweight");
         }else if(bmi>22.5 && bmi< 29.5){
              Messagetf.setText("You are Ideal Weight");
         }else if (bmi>29.5 && bmi< 32.9){
             Messagetf.setText("You are Over Weight");
         }else{
          Messagetf.setText("You are Obese");
     }
     }
     
 /*  Was suppose to update the BMI progress table in database- not working causing error
     Connection con = null;
        ResultSet rs = null;
        int n = 0;
        PreparedStatement pst = null;
       DBConnection db = new DBConnection();
      try{
          
        
            double w1 = Double.parseDouble(weight);
         double h1 = Double.parseDouble(height);
         
         double bmi1 = w1/(h1*h1);
            
          String sql = "insert into bmi progress values ( ?, ?)";
          pst = con.prepareStatement(sql);
        
           pst.setInt(1, Integer.parseInt(PatientIDtf.getText()));
           pst.setDouble(2,bmi1);
            pst.executeUpdate();
            
             JOptionPane.showMessageDialog(null,"successfully added to database");
           
      }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error");
      }*/
     
    }//GEN-LAST:event_CalculateBMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMICalculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMICalculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMICalculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMICalculator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMICalculator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateBMI;
    private javax.swing.JButton Displaybutton;
    private javax.swing.JRadioButton FRadioButton;
    private javax.swing.JLabel Genderlbl;
    private javax.swing.JTextField Gendertf;
    private javax.swing.JLabel Heightlbl;
    private javax.swing.JTextField Heighttf;
    private javax.swing.JRadioButton MRadioButton;
    private javax.swing.JLabel Messagelbl;
    private javax.swing.JTextField Messagetf;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JTextField Nametf;
    private javax.swing.JLabel PatientIDlbl;
    private javax.swing.JTextField PatientIDtf;
    private javax.swing.JLabel Weightlbl;
    private javax.swing.JTextField Weighttf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
